### PR TITLE
Feature/jwt support

### PR DESCRIPTION
**Pull request by asheliahut**
This adds in support for jwt based tokens using https://github.com/eljam/guzzle-jwt-middleware

### CODE REVIEW

**Comment by asheliahut** [comment]
@rccrdpccl

**Comment by rccrdpccl** [comment]
Thanks for your contribution @asheliahut 

I believe eljam/guzzle-jwt-middleware is another implementation with more or less the same functionality of softonic/guzzle-oauth2-middleware which uses league/oauth2-client underneath.

Any reason why we cannot achieve the same result with guzzle-oauth2-middleware?

**Comment by asheliahut** [comment]
@rccrdpccl The more I look at it, It definitely is possible to implemenet using the guzzle-oauth2-middleware. I will say though the reason I didn't go that path originally is because I assumed that it was really just Oauth2. The naming is really terrible. From looking at their codebase I actually have to specify oauth2 as the auth type to get my headers for "Authorization Bearer" when that is completely wrong for me to specify that when using JWT it is not Oauth2. 

That being said, I can go ahead and use the same one already built in, but the code will not be a proper representation of what is happening, because of the way that guzzle-oauth2-middleware is written.

This library does not implement or use league/oauth2-client as it is not a oauth2 spec auth.

**Comment by rccrdpccl** [comment]
As far as I understand, OAuth2 specifies how the tokens are _transferred_, JWT defines the token _format_.

If you are not using oauth2 to retrieve your JWT token, maybe it makes sense to use another guzzle middleware, but I would not integrate it in this library as it is very custom to your use case. However, it might be a good idea to have a builder method that produces a graphql client instance given a guzzle instance - do you think this would solve your problem?

**Comment by asheliahut** [comment]
Yes it is true that OAuth2 supports jwt tokens and supports distribution of them, but there is a defined pattern to using JWT purely as from a JWT generator to validate your APIs. That is a very common practice and would argue that it isn't a very specifc use case:
https://auth0.com/learn/json-web-tokens/
https://jwt.io/introduction/

Although I do like your idea though. That way you can also rip out the Oauth2 middleware from the package as well.

**Pull request closed without merging**
