### PR TITLE
added functionality to upload a file to graphQL endpoint

### PR DESCRIPTION
**Pull request by timbertens**
graphQL file upload is a bit different from regular queries or other mutations. This pull requests adds a new function to deal with a file upload during mutation

### CODE REVIEW

**Comment by rccrdpccl** [comment]
GraphQL does not specify if/how file upload should be handled (https://facebook.github.io/graphql/June2018/)
It seems that apollo server implemented this, following this specs proposal: https://github.com/jaydenseric/graphql-multipart-request-spec

I believe we can not merge this into master, but if you are willing to implement above mentioned specs, I guess we could create an experimental branch (which won't ensure BC) and merge it there. Eventually we could merge it to master if/when specs become official. What do you think @joskfg ?

**Comment by joskfg** [comment]
I agree. As the [upload file](https://github.com/jaydenseric/graphql-multipart-request-spec) spec is not official (not even in the 20 nov draft) I think that it is a good idea to release some experimental branch for that features not officially supported.

As I can see, the spec is different from the implemented. @timbertens, Where did you find that specification?

**Comment by timbertens** [comment]
yeah, I see the implementation i'm using is actually different than the proposal. 
I'm doing some integration on https://developer.clearfacts.be/#upload-a-sales-invoice-through-a-mutation but it seems they use a specific workaround for non-existing spec.  Argh, standards :-)

**Comment by joskfg** [comment]
Due to this is not the standard way and there is no changes since a few month ago, I close this PR.

**Pull request closed without merging**
